#!/usr/bin/env bash
set -e

if [ "$#" -gt 0 ]; then
    exec "$@"
fi

# Use the PORT environment variable provided by Render, or default to 8080
export PORT=${PORT:-8080}

# Replace the ${PORT} variable in the Nginx configuration
envsubst '${PORT}' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf.tmp
mv /etc/nginx/conf.d/default.conf.tmp /etc/nginx/conf.d/default.conf

# The Docker build context excludes runtime storage directories, so recreate
# Laravel's writable paths before any Artisan cache command touches them.
mkdir -p \
    /var/www/storage/framework/cache/data \
    /var/www/storage/framework/sessions \
    /var/www/storage/framework/testing \
    /var/www/storage/framework/views \
    /var/www/storage/logs \
    /var/www/bootstrap/cache

chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
chmod -R 775 /var/www/storage /var/www/bootstrap/cache

# Cache configuration, routes, and views for production
php artisan config:cache
php artisan route:cache
php artisan view:cache

# Ensure permissions include files generated by the cache commands
chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
chmod -R 775 /var/www/storage /var/www/bootstrap/cache

# Run migrations during deploy. Render free instances do not provide Shell access.
if [ "${RENDER_DB_FRESH:-false}" = "true" ]; then
    php artisan migrate:fresh --force --no-interaction -vvv
else
    php artisan migrate --force --no-interaction -vvv
fi

# Start PHP-FPM in background
php-fpm -D

# Start Nginx in foreground
nginx -g "daemon off;"
