<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Teacher Attendance Reports</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1f2937; line-height: 1.4; padding: 10px; margin: 0; }
        .header { text-align: center; margin-bottom: 25px; border-bottom: 2px solid #2563eb; padding-bottom: 12px; }
        .header h1 { margin: 0; font-size: 22px; text-transform: uppercase; letter-spacing: 1.5px; color: #2563eb; }
        .header p { margin: 5px 0 0 0; font-size: 10px; color: #4b5563; font-weight: bold; letter-spacing: 1px; }
        
        .meta-grid { display: table; width: 100%; margin-bottom: 20px; border: 1px solid #e5e7eb; background: #f9fafb; }
        .meta-item { display: table-cell; padding: 10px 14px; border-right: 1px solid #e5e7eb; width: 25%; }
        .meta-item:last-child { border-right: none; }
        .meta-label { font-size: 8px; color: #6b7280; text-transform: uppercase; display: block; margin-bottom: 4px; font-weight: bold; }
        .meta-value { font-size: 12px; font-weight: bold; color: #111827; }

        .summary-title { font-size: 11px; font-weight: bold; color: #374151; text-transform: uppercase; margin-bottom: 8px; font-family: monospace; letter-spacing: 0.5px; }
        .summary-grid { display: table; width: 100%; margin-bottom: 25px; border-collapse: collapse; }
        .summary-box { display: table-cell; width: 16.6%; padding: 10px; border: 1px solid #e5e7eb; text-align: center; background: #fff; }
        .summary-num { font-size: 18px; font-weight: bold; margin-top: 3px; }

        .section-title { font-size: 12px; font-weight: bold; background: #f3f4f6; padding: 6px 12px; border-left: 4px solid #2563eb; margin-top: 20px; margin-bottom: 10px; text-transform: uppercase; color: #1f2937; letter-spacing: 0.5px; }

        table { width: 100%; border-collapse: collapse; margin-top: 5px; }
        th { background: #374151; color: #ffffff; font-size: 9px; text-transform: uppercase; padding: 8px 10px; text-align: left; font-weight: bold; border: 1px solid #374151; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; border-left: 1px solid #e5e7eb; border-right: 1px solid #e5e7eb; font-size: 9.5px; color: #374151; }
        tr:nth-child(even) { background: #f9fafb; }
        
        .badge { font-weight: bold; padding: 2px 6px; border-radius: 99px; font-size: 8px; text-transform: uppercase; display: inline-block; border: 1px solid transparent; }
        .badge.present, .badge.on_time, .badge.completed { background: #dcfce7; color: #15803d; border-color: #bbf7d0; }
        .badge.late, .badge.very_late, .badge.early_leave, .badge.missing_check_out { background: #fef3c7; color: #b45309; border-color: #fde68a; }
        .badge.absent { background: #fee2e2; color: #b91c1c; border-color: #fca5a5; }
        .badge.permission { background: #f3e8ff; color: #6b21a8; border-color: #e9d5ff; }

        .footer { margin-top: 30px; font-size: 8.5px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Teacher Attendance Report</h1>
        <p>OFFICIAL ATTENDANCE MONITORING RECORD · ATTENDAI SYSTEM</p>
    </div>

    <div class="meta-grid">
        <div class="meta-item">
            <span class="meta-label">Selected Period</span>
            <span class="meta-value">{{ $periodLabel ?? ($from->format('M d, Y') . ' - ' . $to->format('M d, Y')) }}</span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Target Teacher</span>
            <span class="meta-value">{{ $teacherName }}</span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Generated By</span>
            <span class="meta-value">{{ auth()->user()->name ?? 'System Admin' }}</span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Exported Timestamp</span>
            <span class="meta-value">{{ date('M d, Y @ h:i A') }}</span>
        </div>
    </div>

    <div class="summary-title">📈 Metric Performance Indicators</div>
    <div class="summary-grid">
        <div class="summary-box">
            <span class="meta-label">Scheduled</span>
            <div class="summary-num" style="color: #2563eb;">{{ $summary['scheduled'] }}</div>
        </div>
        <div class="summary-box">
            <span class="meta-label">Completed</span>
            <div class="summary-num" style="color: #16a34a;">{{ $summary['completed'] }}</div>
        </div>
        <div class="summary-box">
            <span class="meta-label">Late</span>
            <div class="summary-num" style="color: #ea580c;">{{ $summary['late'] }}</div>
        </div>
        <div class="summary-box">
            <span class="meta-label">Absent</span>
            <div class="summary-num" style="color: #dc2626;">{{ $summary['absent'] }}</div>
        </div>
        <div class="summary-box">
            <span class="meta-label">Teaching Hours</span>
            <div class="summary-num" style="color: #9333ea;">{{ number_format($summary['teaching_hours'], 1) }}</div>
        </div>
        <div class="summary-box">
            <span class="meta-label">Attendance Rate</span>
            <div class="summary-num" style="color: #0d9488;">{{ $summary['attendance_percentage'] }}%</div>
        </div>
    </div>

    <h2 class="section-title">📊 Registry Log Entries ({{ $sessions->count() }} records · {{ strtoupper($groupBy ?? 'department') }})</h2>
    @if($sessions->isEmpty())
        <p style="font-size: 11px; color: #666; font-style: italic; padding-left: 10px;">No records match the selected filter criteria.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th style="width: 12%;">Date</th>
                    <th style="width: 20%;">Teacher</th>
                    <th style="width: 25%;">Subject / Group</th>
                    <th style="width: 11%; text-align: center;">Status</th>
                    <th style="width: 24%;">Schedule vs Actual Time</th>
                    <th style="width: 8%; text-align: right;">Hours</th>
                </tr>
            </thead>
            <tbody>
                @foreach($sessions as $session)
                    <tr>
                        <td style="font-family: monospace;">
                            <strong>{{ $session->attendance_date?->format('Y-m-d') }}</strong>
                            <div style="font-size: 8px; color: #6b7280; margin-top: 1px;">{{ $session->attendance_date?->format('l') }}</div>
                        </td>
                        <td>
                            <div style="font-weight: bold; color: #111827;">{{ $session->teacher->user->name ?? 'Unknown' }}</div>
                            <div style="font-size: 8px; color: #6b7280; margin-top: 1px;">{{ $session->teacher->department->name ?? 'No dept.' }}</div>
                        </td>
                        <td>
                            <div style="font-weight: 500;">{{ $session->subject->name ?? '-' }}</div>
                            <div style="font-size: 8.5px; color: #4b5563; font-family: monospace; margin-top: 2px;">
                                {{ $session->classGroup->name ?? $session->classRoom->name ?? 'No Group' }}
                            </div>
                        </td>
                        <td style="text-align: center;">
                            @php
                                $statusLabel = str_replace('_', ' ', strtoupper($session->attendance_status));
                            @endphp
                            <span class="badge {{ $session->attendance_status }}">{{ $statusLabel }}</span>
                        </td>
                        <td style="font-family: monospace; font-size: 9px; line-height: 1.3;">
                            <div><span style="color: #6b7280;">SCHED:</span> {{ $session->scheduled_start_time?->format('H:i') }} - {{ $session->scheduled_end_time?->format('H:i') }}</div>
                            <div style="margin-top: 1px;"><span style="color: #6b7280;">ACTUAL:</span> {{ $session->check_in_time?->format('H:i') ?? '-' }} - {{ $session->check_out_time?->format('H:i') ?? '-' }}</div>
                        </td>
                        <td style="text-align: right; font-family: monospace; font-weight: bold; font-size: 11px; color: #2563eb;">
                            {{ number_format($session->actual_teaching_hours, 1) }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Confidential Document · Generated on {{ date('M d, Y @ h:i A') }} · ATTENDAI Intelligence Network
    </div>
</body>
</html>
